version: '3.8'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:18.6.1-ce.0'
    restart: always
    # Use the service name for internal hostname resolution
    hostname: 'gitlab' 
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Set the external URL here to match the host's port 80
        external_url 'http://localhost:80'
        gitlab_rails['initial_root_password'] = 'Qwerty_123' # Change this
        # Add other configurations here
    ports:
      # Map the container's port 80 to the host's port 80
      - '80:80' 
      - '443:443'
      - '22:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    networks:
      - gitlab-network

  gitlab-runner:
    # should ideally match the major and minor version of your GitLab instance
    image: 'gitlab/gitlab-runner:v18.6.5'
    container_name: gitlab-runner
    restart: always
    depends_on:
      - gitlab
    volumes:
      - './gitlab-runner/config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - gitlab-network

networks:
  gitlab-network:
    driver: bridge
