services:
  gitlab:
    image: 'gitlab/gitlab-ce:18.6.1-ce.0'
    restart: always
    # Use the service name for internal hostname resolution
    hostname: 'gitlab' 
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Set the external URL here to match the host's port 80, custom port cause failures
        external_url 'http://localhost:80'
        gitlab_rails['initial_root_password'] = 'Qwerty_123' # Change this
        # Add other configurations here
    ports:
      # Map the container's port 80 to the host's port 80
      - '80:80' 
      - '443:443'
      - '22:22'
    volumes:
# WARNING: Uploading artifacts as "archive" to coordinator... POST
# http://host.docker.internal/api/v4/jobs/25/artifacts: 500 Internal Server Error
# correlation_id=01KC1MQ2JKT23W79Y7J5WKXHSN id=25 responseStatus=500 Internal Server Error
# status=500 token=64_SaXi9- WARNING: Retrying... context=artifacts-uploader error=invalid
# argument
# link: https://gitlab.com/gitlab-org/gitlab/-/issues/444271
# do not use windows volume, but wsl 2 volume
# \\wsl.localhost\docker-desktop\var
      - '/home/gitlab/data/config:/etc/gitlab'   # - './gitlab/config:/etc/gitlab'
      - '/home/gitlab/data/logs:/var/log/gitlab' # - './gitlab/logs:/var/log/gitlab'
      - '/home/gitlab/data/data:/var/opt/gitlab' # - './gitlab/data:/var/opt/gitlab'
    networks:
      - gitlab-network

  gitlab-runner:
    # should ideally match the major and minor version of your GitLab instance
    image: 'gitlab/gitlab-runner:v18.6.5'
    container_name: gitlab-runner
    restart: always
    depends_on:
      - gitlab
    #https://chatgpt.com/c/6936a1ec-83a4-8327-b2c8-65826af6d799
    #Windows cannot preserve Linux permissions, so:
    #- registration breaks
    #- jobs fail
    #- artifacts fail
    #- Docker in Docker fails
    #- runners keep losing their config
    #- permission errors appear (exit code 127, etc.)
    # comment this
    # When you need to back it up:
    # docker cp gitlab-runner:/etc/gitlab-runner .
    #volumes:
    #  - './gitlab-runner/config:/etc/gitlab-runner'
    #  - '/var/run/docker.sock:/var/run/docker.sock'
    volumes:
      - runner-config:/etc/gitlab-runner             # LINUX VOLUME (SAFE)
      - /var/run/docker.sock:/var/run/docker.sock    # REQUIRED FOR DOCKER EXECUTOR
    networks:
      - gitlab-network
volumes:
  runner-config:
networks:
  gitlab-network:
    driver: bridge
